FIND_PATH(ARMADILLO_INCLUDE_DIR armadillo $ENV{ARMADILLO_HOME}/include ${SCAFFOLD_INSTALL_DIR}/include)
FIND_LIBRARY(ARMADILLO_LIBS armadillo $ENV{ARMADILLO_HOME}/lib $ENV{ARMADILLO_HOME}/lib64 ${SCAFFOLD_INSTALL_DIR}/lib)
IF(ARMADILLO_INCLUDE_DIR AND ARMADILLO_LIBS)
    INCLUDE_DIRECTORIES(${ARMADILLO_INCLUDE_DIR})
    LINK_LIBRARIES(${ARMADILLO_LIBS})
    MESSAGE(STATUS "ARMADILLO_INCLUDE_DIR=${ARMADILLO_INCLUDE_DIR}")
    MESSAGE(STATUS "ARMADILLO_LIBS=${ARMADILLO_LIBS}")
ELSE()
    ExternalProject_Add(
      armadillo_project
      URL http://sourceforge.net/projects/arma/files/armadillo-4.450.4.tar.gz
      SOURCE_DIR ${SCAFFOLD_DEPENDS_DIR}/armadillo
      CMAKE_COMMAND cmake . -DCMAKE_INSTALL_PREFIX=${SCAFFOLD_INSTALL_DIR}
    )
    SET(ARMADILLO_LIBS armadillo)
    MESSAGE(STATUS "ARMADILLO_HOME not found. Installing in SCAFFOLD_DEPENDS_DIR.")
ENDIF()
