FIND_PATH(EINSPLINE_INCLUDE_DIR einspline $ENV{EINSPLINE_HOME}/include ${SCAFFOLD_INSTALL_DIR}/include)
FIND_LIBRARY(EINSPLINE_LIBS einspline $ENV{EINSPLINE_HOME}/lib $ENV{EINSPLINE_HOME}/lib64 ${SCAFFOLD_INSTALL_DIR}/lib)
IF(EINSPLINE_INCLUDE_DIR AND EINSPLINE_LIBS)
    INCLUDE_DIRECTORIES(${EINSPLINE_INCLUDE_DIR})
    LINK_LIBRARIES(${EINSPLINE_LIBS})
    MESSAGE(STATUS "EINSPLINE_INCLUDE_DIR=${EINSPLINE_INCLUDE_DIR}")
    MESSAGE(STATUS "EINSPLINE_LIBS=${EINSPLINE_LIBS}")
ELSE()
    ExternalProject_Add(
      meinspline_project
      URL http://github.com/etano/meinspline/archive/master.tar.gz
      SOURCE_DIR ${SCAFFOLD_DEPENDS_DIR}/meinspline
      CONFIGURE_COMMAND ${SCAFFOLD_DEPENDS_DIR}/meinspline/configure --enable-sse --prefix=${SCAFFOLD_INSTALL_DIR}
      BUILD_COMMAND make
    )
    SET(EINSPLINE_LIBS einspline)
    MESSAGE(STATUS "EINSPLINE_HOME not found. Installing in SCAFFOLD_DEPENDS_DIR.")
ENDIF()
