FIND_PATH(MATRIX_INCLUDE_DIR armadillo $ENV{ARMADILLO_HOME}/include ${SCAFFOLD_INSTALL_DIR}/include)
FIND_LIBRARY(MATRIX_LIBS armadillo $ENV{ARMADILLO_HOME}/lib $ENV{ARMADILLO_HOME}/lib64 ${SCAFFOLD_INSTALL_DIR}/lib)
IF(MATRIX_INCLUDE_DIR AND MATRIX_LIBS)
    INCLUDE_DIRECTORIES(${MATRIX_INCLUDE_DIR})
    LINK_LIBRARIES(${MATRIX_LIBS})
    MESSAGE(STATUS "MATRIX_INCLUDE_DIR=${MATRIX_INCLUDE_DIR}")
    MESSAGE(STATUS "MATRIX_LIBS=${MATRIX_LIBS}")
ELSE()
    ExternalProject_Add(
      armadillo_project
      URL http://sourceforge.net/projects/arma/files/armadillo-4.450.4.tar.gz
      SOURCE_DIR ${SCAFFOLD_DEPENDS_DIR}/armadillo
      CMAKE_COMMAND cmake . -DCMAKE_INSTALL_PREFIX=${SCAFFOLD_INSTALL_DIR}
    )
    SET(MATRIX_LIBS armadillo)
    MESSAGE(STATUS "ARMADILLO_HOME not found. Installing in SCAFFOLD_DEPENDS_DIR.")
ENDIF()
