FIND_PATH(HDF5_INCLUDE_DIR hdf5.h HINTS $ENV{HDF5_HOME}/include ${SCAFFOLD_INSTALL_DIR}/include NO_DEFAULT_PATH)
FIND_LIBRARY(HDF5_LIB hdf5 $ENV{HDF5_HOME}/lib $ENV{HDF5_HOME}/lib64 ${SCAFFOLD_INSTALL_DIR}/lib NO_DEFAULT_PATH)
FIND_LIBRARY(HDF5_CPP_LIB hdf5_cpp $ENV{HDF5_HOME}/lib $ENV{HDF5_HOME}/lib64 ${SCAFFOLD_INSTALL_DIR}/lib NO_DEFAULT_PATH)
SET(HDF5_LIBS ${HDF5_LIB} ${HDF5_CPP_LIB})
IF(HDF5_INCLUDE_DIR AND HDF5_LIBS)
    INCLUDE_DIRECTORIES(${HDF5_INCLUDE_DIR})
    LINK_LIBRARIES(${HDF5_LIBS})
    MESSAGE(STATUS "HDF5_INCLUDE_DIR=${HDF5_INCLUDE_DIR}")
    MESSAGE(STATUS "HDF5_LIBS=${HDF5_LIBS}")
ELSE()
    ExternalProject_Add(
      hdf5_project
      URL http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.13.tar.gz
      SOURCE_DIR ${SCAFFOLD_DEPENDS_DIR}/hdf5
      CONFIGURE_COMMAND ${SCAFFOLD_DEPENDS_DIR}/hdf5/configure --prefix=${SCAFFOLD_INSTALL_DIR} --enable-cxx
      BUILD_COMMAND make
    )
    SET(HDF5_LIBS hdf5 hdf5_cpp)
    MESSAGE(STATUS "HDF5_HOME not found. Installing in SCAFFOLD_DEPENDS_DIR.")
ENDIF()
